# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitmultiverse < Formula
  desc "Multi-account Git identity manager CLI"
  homepage "https://github.com/JahidGittu/Git-Multiverse"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.3.0/GitMultiverse-macOS-amd64-1.3.0.tar.gz"
      sha256 "cdc325e8fd945a774b5d4f9e38f72d1c24c99b7fc136388fdac8707ae49b8fae"

      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.3.0/GitMultiverse-macOS-arm64-1.3.0.tar.gz"
      sha256 "065a72fddaff6646990ab5f77c31ba05f5e1da85d37ef3d6c0a374c52a65266a"

      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.3.0/GitMultiverse-Linux-amd64-1.3.0.tar.gz"
      sha256 "9d1bbdc92e8b4bdd551848e8f0c3467c817ea4765fa75a855fcb0a7caaa317fb"
      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.3.0/GitMultiverse-Linux-arm64-1.3.0.tar.gz"
      sha256 "0e04753ed7bf4f499862719df8b239a14a7613c66b90747728f4cf29314f7208"
      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
  end
end
