# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitmultiverse < Formula
  desc "Multi-account Git identity manager CLI"
  homepage "https://github.com/JahidGittu/Git-Multiverse"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.0.3/GitMultiverse-macOS-amd64-1.0.3.tar.gz"
      sha256 "f8fae37e67265a0cacd89885a9d567946c0229e70eda778928fb00feb737c4e4"

      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.0.3/GitMultiverse-macOS-arm64-1.0.3.tar.gz"
      sha256 "ea4140dff1c463cf4e6c293820240a303d44983087a0c3314119fc31ec27b02b"

      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.0.3/GitMultiverse-Linux-amd64-1.0.3.tar.gz"
      sha256 "a4a30e2f5cba17a57bb5f2f26680224f1ccd901396540b7df0b390088a6ad97e"
      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.0.3/GitMultiverse-Linux-arm64-1.0.3.tar.gz"
      sha256 "91662f60938d89d17d7e7b008b1219abb36710159effab7a907b023a59a9569e"
      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
  end
end
