# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitmultiverse < Formula
  desc "Multi-account Git identity manager CLI"
  homepage "https://github.com/JahidGittu/Git-Multiverse"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.0.1/gitmultiverse_1.0.1_darwin_amd64.tar.gz"
      sha256 "d8b52adddc81c61afee693a3eeb77b7848967ea58168234217c0156fb04eab2b"

      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.0.1/gitmultiverse_1.0.1_darwin_arm64.tar.gz"
      sha256 "43cedeb40ac912caefdc979f0ffbd6aaa035f7ab3f3ec3b6bf641036571e5db2"

      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.0.1/gitmultiverse_1.0.1_linux_amd64.tar.gz"
      sha256 "2d5a06b1dc06f52479ebbd48d9e8ce880345fb779016128583cb44eea75eeeb2"
      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JahidGittu/Git-Multiverse/releases/download/v1.0.1/gitmultiverse_1.0.1_linux_arm64.tar.gz"
      sha256 "0adca59748df1ad3a4daa28157c7ececf5d0c1990dac771e1bd51a5282b4f96a"
      define_method(:install) do
        bin.install "gitm"
        bin.install "gitmultiverse-server"
        bin.install "git-interceptor"
      end
    end
  end
end
